using System.Globalization;

namespace PixelFlux.Core.Localisation;

/// <summary>
/// Every piece of user-visible text in PixelFlux, and the machinery to say it in another
/// language.
/// </summary>
/// <remarks>
/// <para>
/// A plain dictionary per language rather than .resx satellite assemblies. The reasons are
/// specific rather than contrarian: PixelFlux ships as a single unpackaged executable, and
/// satellite assemblies mean a folder of per-culture DLLs that has to survive copying,
/// zipping, and being moved between machines; a translator working on .resx needs Visual
/// Studio; and the catalogue below is directly greppable, which is what makes it possible to
/// prove no English is left hardcoded in the components.
/// </para>
/// <para>
/// <b>Keys are dotted and semantic</b> — <c>gallery.empty.title</c>, not <c>Msg17</c> and not
/// the English text itself. Using the English as the key looks convenient and then locks every
/// language to English's grammar the moment a string needs to change.
/// </para>
/// <para>
/// <b>Missing translations fall back to English and are never blank.</b> A partially translated
/// build is the normal state of any real localisation effort, and a UI that shows empty buttons
/// for the untranslated half is worse than one that shows English.
/// </para>
/// </remarks>
public sealed class Strings
{
    /// <summary>A language PixelFlux can display.</summary>
    /// <param name="Code">BCP-47 culture code, for example <c>pt-BR</c>.</param>
    /// <param name="EnglishName">Name in English, for logs and settings search.</param>
    /// <param name="NativeName">Name as speakers of it write it — what the picker shows.</param>
    /// <param name="RightToLeft">Whether the script runs right to left.</param>
    public readonly record struct Language(string Code, string EnglishName, string NativeName, bool RightToLeft);

    /// <summary>The languages this build ships.</summary>
    /// <remarks>
    /// The set is deliberately not five European languages that all behave identically. Arabic
    /// is here because right-to-left layout breaks assumptions that never surface otherwise, and
    /// Japanese because it has no spaces between words and no plural forms, which catches string
    /// concatenation that only works in English.
    /// </remarks>
    public static readonly IReadOnlyList<Language> Available =
    [
        new("en", "English", "English", false),
        new("es", "Spanish", "Español", false),
        new("ja", "Japanese", "日本語", false),
        new("ar", "Arabic", "العربية", true),
    ];

    private static readonly Dictionary<string, Dictionary<string, string>> Catalogue = new(StringComparer.OrdinalIgnoreCase)
    {
        ["en"] = new(StringComparer.Ordinal)
        {
            ["search.placeholder"] = "dogs on a beach at sunset",
            ["search.corrected"] = "“{0}” → {1}",
            ["search.byMeaning"] = "including matches by meaning",
            ["search.describe"] = "Describe photos",
            ["describe.action"] = "Read photos",
            ["describe.working"] = "Reading photos",
            ["describe.done"] = "Read {0} photos",
            ["describe.coverage"] = "{0} of {1} photos have been read",
            ["plate.described"] = "What PixelFlux read",
            ["search.describing"] = "Describing photos",
            ["search.described"] = "{0} of {1} photos searchable by meaning",
            ["search.label"] = "Search your photos",

            ["tool.filters"] = "Filters",
            ["tool.sort"] = "Sort",
            ["tool.smaller"] = "Smaller frames",
            ["tool.larger"] = "Larger frames",
            ["tool.add"] = "Add photos",
            ["tool.importing"] = "Importing…",
            ["tool.shortcuts"] = "Keyboard shortcuts",

            ["sort.captured.desc"] = "Newest first",
            ["sort.captured.asc"] = "Oldest first",
            ["sort.indexed.desc"] = "Recently added",
            ["sort.filename"] = "Filename",
            ["sort.rating.desc"] = "Highest rated",
            ["sort.size.desc"] = "Largest file",
            ["sort.camera"] = "By camera",
            ["sort.folder"] = "By folder",
            ["sort.shuffle"] = "Shuffle",

            ["heading.all"] = "All photos",
            ["heading.search"] = "Search",
            ["heading.filtered"] = "Filtered",
            ["heading.frames"] = "{0} frames · {1}",

            ["filter.title"] = "Filter",
            ["filter.clearAll"] = "Clear all",
            ["filter.rating"] = "Rating",
            ["filter.camera"] = "Camera",
            ["filter.folder"] = "Folder",
            ["filter.tag"] = "Tag",
            ["filter.city"] = "City",
            ["filter.country"] = "Country",
            ["filter.place"] = "Place",
            ["filter.favourites"] = "Favourites only",
            ["filter.starsAndUp"] = "{0} stars and up",
            ["filter.any"] = "any",
            ["filter.remove"] = "Remove this filter",
            ["filter.active"] = "Active filters",

            ["rail.label"] = "Timeline",
            ["rail.showAll"] = "Show all photos",
            ["rail.noPhotos"] = "No photos yet",
            ["rail.emptyMonths"] = "{0} months with no photos",
            ["rail.notAnalysed"] = "some not analysed yet",

            ["empty.none.title"] = "No photos yet",
            ["empty.none.body"] = "Point PixelFlux at a folder and it will read every image, work out when and where each one was taken, and start describing them in the background.",
            ["empty.filtered.title"] = "Nothing matches",
            ["empty.filtered.body"] = "No photos fit all of these filters at once. Remove one above, or clear them all and start again.",
            ["empty.filtered.action"] = "Clear all filters",

            ["frame.unreadable"] = "Can't read this file",
            ["frame.queued"] = "Waiting to be analysed",

            ["status.photos"] = "photos",
            ["status.shown"] = "shown",
            ["status.unreadable"] = "unreadable",
            ["status.idle"] = "idle",
            ["status.reading"] = "reading files",
            ["status.analysing"] = "analysing {0}",
            ["status.queued"] = "{0} queued",
            ["pipeline.describe"] = "Reading {0}",
            ["pipeline.segment"] = "Finding objects in {0}",
            ["pipeline.faces"] = "Finding faces in {0}",
            ["pipeline.embed"] = "Indexing {0}",
            ["pipeline.waiting"] = "{0} to analyse",
            ["analysis.title"] = "Analysis",
            ["analysis.stage.describe"] = "Read",
            ["analysis.stage.segment"] = "Objects",
            ["analysis.stage.faces"] = "Faces",
            ["analysis.stage.embed"] = "Search index",
            ["analysis.stuck"] = "{0} could not be read.",
            ["analysis.when"] = "When to run",
            ["analysis.mode.always"] = "While open",
            ["analysis.mode.window"] = "Overnight",
            ["analysis.mode.off"] = "Only when I ask",
            ["analysis.from"] = "From",
            ["analysis.to"] = "To",
            ["analysis.gap"] = "Pause between photos",
            ["analysis.gapValue"] = "{0}s",
            ["analysis.runNow"] = "Run now",
            ["analysis.opensAt"] = "Next run at {0}",
            ["analysis.hardware"] = "Hardware",
            ["analysis.accel.auto"] = "Automatic",
            ["analysis.accel.cpu"] = "Processor",
            ["analysis.accel.gpu"] = "Graphics",
            ["analysis.accel.npu"] = "Neural",
            ["analysis.accelRestart"] = "Takes effect next time PixelFlux starts.",
            ["plate.analysis"] = "PENDING",
            ["plate.analysisWaiting"] = "waiting for {0}",
            ["plate.analysisStuck"] = "{0} could not run on this photo",
            ["analysis.accelUsedBy"] = "Used for {0}. The rest is faster on the processor.",
            ["analysis.accelNone"] = "Everything runs on the processor.",
            ["analysis.retry"] = "Try again",
            ["setup.title"] = "Switch on the clever parts",
            ["setup.preamble"] = "PixelFlux works offline, but the models that read your photographs are too large to ship and are not ours to redistribute. Downloading one is the only time this application uses the network. Each is optional and each can wait.",
            ["setup.get"] = "Download",
            ["setup.getAll"] = "Download everything ({0})",
            ["setup.installed"] = "Installed",
            ["setup.stop"] = "Stop",
            ["setup.later"] = "Not now",
            ["setup.done"] = "Done",
            ["sources.title"] = "Where your photos live",
            ["sources.empty"] = "No folders yet. Add one and PixelFlux will import everything beneath it.",
            ["sources.add"] = "Add a folder…",
            ["sources.scan"] = "Scan for new photos",
            ["sources.scanning"] = "Looking…",
            ["sources.remove"] = "Remove",
            ["sources.removeHint"] = "Stop importing from this folder. Photos already imported stay.",
            ["sources.missing"] = "not reachable",
            ["sources.close"] = "Close",
            ["setup.copyleft"] = "This one is AGPL-3.0. Fine for your own photographs; sharing a build that includes it, or running a modified PixelFlux as a service, obliges you to publish your source.",
            ["setup.readTerms"] = "Read the terms",
            ["status.imported"] = "added {0} · {1} already known · {2}s",
            ["status.noAlbum"] = "no album folder found",

            ["viewer.close"] = "Close",
            ["viewer.previous"] = "Previous photo",
            ["viewer.next"] = "Next photo",
            ["plate.frame"] = "Frame",
            ["plate.taken"] = "Taken",
            ["plate.filed"] = "Filed",
            ["plate.camera"] = "Camera",
            ["plate.exposure"] = "Exposure",
            ["plate.size"] = "Size",
            ["plate.place"] = "Place",
            ["plate.saw"] = "What PixelFlux saw",
            ["plate.notAnalysed"] = "Not analysed yet",
            ["plate.queued"] = "queued",
            ["plate.fromExif"] = "From the camera's EXIF",
            ["plate.fromFile"] = "No EXIF date — taken from the file's timestamp",

            ["keys.title"] = "Keyboard shortcuts",
            ["keys.close"] = "Close",
            ["keys.group.navigate"] = "Navigate",
            ["keys.group.filter"] = "Find and filter",
            ["keys.group.view"] = "View",
            ["keys.move"] = "Move between photos",
            ["keys.open"] = "Open the selected photo",
            ["keys.firstLast"] = "First / last photo",
            ["keys.page"] = "Page up / down",
            ["keys.search"] = "Jump to search",
            ["keys.toggleFilters"] = "Show or hide filters",
            ["keys.clear"] = "Clear filters, or close what is open",
            ["keys.zoom"] = "Smaller / larger frames",
            ["keys.help"] = "This list",

            ["crash.title"] = "PixelFlux hit an error",
            ["crash.body"] = "The library is untouched — nothing was written. Reload to carry on, and if it keeps happening the details below are what to report.",
            ["crash.reload"] = "Reload the view",

            ["notFound.title"] = "Nothing here",
            ["notFound.body"] = "That address does not match anything in PixelFlux. Head back to your photos.",
            ["notFound.action"] = "All photos",

            ["albums.title"] = "Albums",
            ["albums.new"] = "New album",
            ["albums.namePlaceholder"] = "Album name",
            ["albums.create"] = "Create",
            ["albums.cancel"] = "Cancel",
            ["albums.none"] = "No albums yet",
            ["albums.all"] = "All photos",
            ["albums.empty"] = "This album is empty. Select photos and add them here.",
            ["albums.rename"] = "Rename",
            ["albums.delete"] = "Delete album",
            ["albums.deleteHint"] = "Deletes the album only. Your photos are not touched.",
            ["albums.dropHere"] = "Drop to add",
            ["albums.duplicateName"] = "There is already an album with that name",

            ["select.count"] = "{0} selected",
            ["select.clear"] = "Clear selection",
            ["select.all"] = "Select all",
            ["select.toggle"] = "Select this photo",
            ["select.addTo"] = "Add to album",
            ["select.moveTo"] = "Move to album",
            ["select.removeFrom"] = "Remove from this album",
            ["select.added"] = "Added {0} to {1}",
            ["select.moved"] = "Moved {0} to {1}",
            ["select.removed"] = "Removed {0} from {1}",
            ["select.alreadyIn"] = "already in this album",

            ["seg.title"] = "What is in this photo",
            ["seg.show"] = "Show what the model found",
            ["seg.hide"] = "Hide the overlay",
            ["seg.none"] = "Nothing recognised in this photo",
            ["seg.findAll"] = "Find every photo with {0}",
            ["seg.coverage"] = "{0}% of the frame",
            ["label.add"] = "Add a keyword",
            ["label.remove"] = "Remove this keyword",
            ["label.rename"] = "Correct this label",
            ["label.saved"] = "Now called {0}",
            ["label.reverted"] = "Back to what the model said",
            ["label.tagged"] = "Added {0}",
            ["label.untagged"] = "Removed {0}",
            ["filter.object"] = "In the photo",

            // ---- faces -------------------------------------------------------------------
            ["faces.title"] = "Faces",
            ["faces.show"] = "Show",
            ["faces.show.people"] = "One card per person",
            ["faces.show.all"] = "Every face",
            ["faces.appears"] = "In {0} photos",
            ["faces.appearsOne"] = "In 1 photo",
            ["faces.people"] = "{0} people in {1} photos",
            ["faces.nav.photos"] = "Photos",
            ["faces.nav.faces"] = "Faces",
            ["faces.count"] = "{0} faces in {1} photos",
            ["faces.countOne"] = "1 face in 1 photo",
            ["faces.scan"] = "Find faces",
            ["faces.scanning"] = "Looking for faces",
            ["faces.scanned"] = "Examined {0} photos and found {1} faces",
            ["faces.rescan"] = "Look again",
            ["faces.order"] = "Order",
            ["faces.order.prominence"] = "Most prominent",
            ["faces.order.newest"] = "Newest photo",
            ["faces.order.oldest"] = "Oldest photo",
            ["faces.order.confidence"] = "Most certain",
            ["faces.confidence"] = "Certainty",
            ["faces.confidence.all"] = "Everything found",
            ["faces.confidence.likely"] = "Likely faces",
            ["faces.confidence.certain"] = "Certain faces only",
            ["faces.open"] = "Open the photo this face is in",
            ["faces.inPhoto"] = "In {0}",
            ["faces.share"] = "{0}% of the frame",
            ["faces.empty.title"] = "No faces yet",
            ["faces.empty.body"] = "Nothing here has been looked at for faces. The search runs on this computer and no photo leaves it.",
            ["faces.none.title"] = "No faces in this library",
            ["faces.none.body"] = "Every photo has been examined and none of them has a face in it.",
            ["faces.nomodel.title"] = "The face detector is not installed",
            ["faces.nomodel.body"] = "Put face_yunet_2023mar.onnx in {0} and reopen this page.",
            ["faces.privacy"] = "Faces are found on this computer. Nothing is uploaded.",

            // ---- this person ------------------------------------------------------------
            ["person.title"] = "This person",
            ["person.count"] = "{0} photos",
            ["person.countOne"] = "1 photo",
            ["person.back"] = "All faces",
            ["person.find"] = "Find every photo of this person",
            ["person.match"] = "Match",
            ["person.match.strict"] = "Only certain",
            ["person.match.normal"] = "Balanced",
            ["person.match.loose"] = "Include maybes",
            ["person.alike"] = "{0}% alike",
            ["person.thisOne"] = "The face you picked",
            ["person.picked"] = "Picked",
            ["person.none.title"] = "Only this one photo",
            ["person.none.body"] = "No other photo in the library has a face close enough to this one.",
            ["person.small.title"] = "This face is too small to search for",
            ["person.small.body"] = "Comparing faces needs more detail than this one has. Try a photo where the person is closer to the camera.",
            ["person.off.title"] = "Comparing faces is not set up",
            ["person.off.body"] = "Put face_sface_2021dec.onnx in {0}, then find faces again.",
            ["person.stale"] = "Found before face comparison was set up. Find faces again to search by person.",
            ["person.caution"] = "PixelFlux matches faces by appearance, not by name. Check before you trust a match.",

            ["viewer.resetZoom"] = "Reset zoom",
            ["language"] = "Language",
        },

        ["es"] = new(StringComparer.Ordinal)
        {
            ["search.placeholder"] = "perros en la playa al atardecer",
            ["search.corrected"] = "«{0}» → {1}",
            ["search.byMeaning"] = "incluye coincidencias por significado",
            ["search.describe"] = "Analizar fotos",
            ["describe.action"] = "Leer fotos",
            ["describe.working"] = "Leyendo fotos",
            ["describe.done"] = "Se leyeron {0} fotos",
            ["describe.coverage"] = "{0} de {1} fotos han sido leídas",
            ["plate.described"] = "Lo que leyó PixelFlux",
            ["search.describing"] = "Analizando fotos",
            ["search.described"] = "{0} de {1} fotos se pueden buscar por significado",
            ["search.label"] = "Busca en tus fotos",

            ["tool.filters"] = "Filtros",
            ["tool.sort"] = "Orden",
            ["tool.smaller"] = "Marcos más pequeños",
            ["tool.larger"] = "Marcos más grandes",
            ["tool.add"] = "Añadir fotos",
            ["tool.importing"] = "Importando…",
            ["tool.shortcuts"] = "Atajos de teclado",

            ["sort.captured.desc"] = "Más recientes primero",
            ["sort.captured.asc"] = "Más antiguas primero",
            ["sort.indexed.desc"] = "Añadidas recientemente",
            ["sort.filename"] = "Nombre de archivo",
            ["sort.rating.desc"] = "Mejor valoradas",
            ["sort.size.desc"] = "Archivo más grande",
            ["sort.camera"] = "Por cámara",
            ["sort.folder"] = "Por carpeta",
            ["sort.shuffle"] = "Aleatorio",

            ["heading.all"] = "Todas las fotos",
            ["heading.search"] = "Búsqueda",
            ["heading.filtered"] = "Filtradas",
            ["heading.frames"] = "{0} fotogramas · {1}",

            ["filter.title"] = "Filtrar",
            ["filter.clearAll"] = "Borrar todo",
            ["filter.rating"] = "Valoración",
            ["filter.camera"] = "Cámara",
            ["filter.folder"] = "Carpeta",
            ["filter.tag"] = "Etiqueta",
            ["filter.city"] = "Ciudad",
            ["filter.country"] = "País",
            ["filter.place"] = "Lugar",
            ["filter.favourites"] = "Sólo favoritas",
            ["filter.starsAndUp"] = "{0} estrellas o más",
            ["filter.any"] = "cualquiera",
            ["filter.remove"] = "Quitar este filtro",
            ["filter.active"] = "Filtros activos",

            ["rail.label"] = "Cronología",
            ["rail.showAll"] = "Mostrar todas las fotos",
            ["rail.noPhotos"] = "Aún no hay fotos",
            ["rail.emptyMonths"] = "{0} meses sin fotos",
            ["rail.notAnalysed"] = "algunas aún sin analizar",

            ["empty.none.title"] = "Aún no hay fotos",
            ["empty.none.body"] = "Indica una carpeta a PixelFlux y leerá cada imagen, averiguará cuándo y dónde se tomó, y empezará a describirlas en segundo plano.",
            ["empty.filtered.title"] = "No hay coincidencias",
            ["empty.filtered.body"] = "Ninguna foto cumple todos estos filtros a la vez. Quita uno arriba, o bórralos todos y empieza de nuevo.",
            ["empty.filtered.action"] = "Borrar todos los filtros",

            ["frame.unreadable"] = "No se puede leer este archivo",
            ["frame.queued"] = "Esperando análisis",

            ["status.photos"] = "fotos",
            ["status.shown"] = "mostradas",
            ["status.unreadable"] = "ilegibles",
            ["status.idle"] = "inactivo",
            ["status.reading"] = "leyendo archivos",
            ["status.analysing"] = "analizando {0}",
            ["status.queued"] = "{0} en cola",
            ["pipeline.describe"] = "Leyendo {0}",
            ["pipeline.segment"] = "Buscando objetos en {0}",
            ["pipeline.faces"] = "Buscando rostros en {0}",
            ["pipeline.embed"] = "Indexando {0}",
            ["pipeline.waiting"] = "{0} por analizar",
            ["analysis.title"] = "Análisis",
            ["analysis.stage.describe"] = "Lectura",
            ["analysis.stage.segment"] = "Objetos",
            ["analysis.stage.faces"] = "Rostros",
            ["analysis.stage.embed"] = "Índice",
            ["analysis.stuck"] = "{0} no se pudieron leer.",
            ["analysis.when"] = "Cuándo ejecutar",
            ["analysis.mode.always"] = "Mientras esté abierto",
            ["analysis.mode.window"] = "De noche",
            ["analysis.mode.off"] = "Solo cuando lo pida",
            ["analysis.from"] = "Desde",
            ["analysis.to"] = "Hasta",
            ["analysis.gap"] = "Pausa entre fotos",
            ["analysis.gapValue"] = "{0}s",
            ["analysis.runNow"] = "Ejecutar ahora",
            ["analysis.opensAt"] = "Próxima ejecución a las {0}",
            ["analysis.hardware"] = "Hardware",
            ["analysis.accel.auto"] = "Automático",
            ["analysis.accel.cpu"] = "Procesador",
            ["analysis.accel.gpu"] = "Gráficos",
            ["analysis.accel.npu"] = "Neuronal",
            ["analysis.accelRestart"] = "Se aplicará la próxima vez que inicie PixelFlux.",
            ["plate.analysis"] = "PENDIENTE",
            ["plate.analysisWaiting"] = "esperando {0}",
            ["plate.analysisStuck"] = "{0} no pudo ejecutarse en esta foto",
            ["analysis.accelUsedBy"] = "Se usa para {0}. El resto es más rápido en el procesador.",
            ["analysis.accelNone"] = "Todo se ejecuta en el procesador.",
            ["analysis.retry"] = "Reintentar",
            ["setup.title"] = "Activar las funciones inteligentes",
            ["setup.preamble"] = "PixelFlux funciona sin conexión, pero los modelos que leen tus fotos son demasiado grandes para incluirlos y no podemos redistribuirlos. Descargar uno es la única vez que esta aplicación usa la red. Todos son opcionales y pueden esperar.",
            ["setup.get"] = "Descargar",
            ["setup.getAll"] = "Descargar todo ({0})",
            ["setup.installed"] = "Instalado",
            ["setup.stop"] = "Detener",
            ["setup.later"] = "Ahora no",
            ["setup.done"] = "Listo",
            ["sources.title"] = "Dónde están tus fotos",
            ["sources.empty"] = "Aún no hay carpetas. Añade una y PixelFlux importará todo lo que contenga.",
            ["sources.add"] = "Añadir carpeta…",
            ["sources.scan"] = "Buscar fotos nuevas",
            ["sources.scanning"] = "Buscando…",
            ["sources.remove"] = "Quitar",
            ["sources.removeHint"] = "Dejar de importar de esta carpeta. Las fotos ya importadas se conservan.",
            ["sources.missing"] = "no disponible",
            ["sources.close"] = "Cerrar",
            ["setup.copyleft"] = "Este es AGPL-3.0. Está bien para tus propias fotos; compartir una versión que lo incluya, o ejecutar un PixelFlux modificado como servicio, te obliga a publicar tu código.",
            ["setup.readTerms"] = "Leer los términos",
            ["status.imported"] = "añadidas {0} · {1} ya conocidas · {2}s",
            ["status.noAlbum"] = "no se encontró la carpeta del álbum",

            ["viewer.close"] = "Cerrar",
            ["viewer.previous"] = "Foto anterior",
            ["viewer.next"] = "Foto siguiente",
            ["plate.frame"] = "Fotograma",
            ["plate.taken"] = "Tomada",
            ["plate.filed"] = "Archivada",
            ["plate.camera"] = "Cámara",
            ["plate.exposure"] = "Exposición",
            ["plate.size"] = "Tamaño",
            ["plate.place"] = "Lugar",
            ["plate.saw"] = "Lo que vio PixelFlux",
            ["plate.notAnalysed"] = "Aún sin analizar",
            ["plate.queued"] = "en cola",
            ["plate.fromExif"] = "Del EXIF de la cámara",
            ["plate.fromFile"] = "Sin fecha EXIF — tomada de la marca de tiempo del archivo",

            ["keys.title"] = "Atajos de teclado",
            ["keys.close"] = "Cerrar",
            ["keys.group.navigate"] = "Navegar",
            ["keys.group.filter"] = "Buscar y filtrar",
            ["keys.group.view"] = "Ver",
            ["keys.move"] = "Moverse entre fotos",
            ["keys.open"] = "Abrir la foto seleccionada",
            ["keys.firstLast"] = "Primera / última foto",
            ["keys.page"] = "Página arriba / abajo",
            ["keys.search"] = "Ir a la búsqueda",
            ["keys.toggleFilters"] = "Mostrar u ocultar filtros",
            ["keys.clear"] = "Borrar filtros, o cerrar lo abierto",
            ["keys.zoom"] = "Marcos más pequeños / grandes",
            ["keys.help"] = "Esta lista",

            ["crash.title"] = "PixelFlux encontró un error",
            ["crash.body"] = "La biblioteca está intacta — no se escribió nada. Recarga para continuar; si sigue ocurriendo, informa de los detalles de abajo.",
            ["crash.reload"] = "Recargar la vista",

            ["notFound.title"] = "Aquí no hay nada",
            ["notFound.body"] = "Esa dirección no corresponde a nada en PixelFlux. Vuelve a tus fotos.",
            ["notFound.action"] = "Todas las fotos",

            ["albums.title"] = "Álbumes",
            ["albums.new"] = "Nuevo álbum",
            ["albums.namePlaceholder"] = "Nombre del álbum",
            ["albums.create"] = "Crear",
            ["albums.cancel"] = "Cancelar",
            ["albums.none"] = "Aún no hay álbumes",
            ["albums.all"] = "Todas las fotos",
            ["albums.empty"] = "Este álbum está vacío. Selecciona fotos y añádelas aquí.",
            ["albums.rename"] = "Cambiar nombre",
            ["albums.delete"] = "Eliminar álbum",
            ["albums.deleteHint"] = "Sólo elimina el álbum. Tus fotos no se tocan.",
            ["albums.dropHere"] = "Suelta para añadir",
            ["albums.duplicateName"] = "Ya existe un álbum con ese nombre",

            ["select.count"] = "{0} seleccionadas",
            ["select.clear"] = "Quitar selección",
            ["select.all"] = "Seleccionar todo",
            ["select.toggle"] = "Seleccionar esta foto",
            ["select.addTo"] = "Añadir al álbum",
            ["select.moveTo"] = "Mover al álbum",
            ["select.removeFrom"] = "Quitar de este álbum",
            ["select.added"] = "Se añadieron {0} a {1}",
            ["select.moved"] = "Se movieron {0} a {1}",
            ["select.removed"] = "Se quitaron {0} de {1}",
            ["select.alreadyIn"] = "ya está en este álbum",

            ["seg.title"] = "Qué hay en esta foto",
            ["seg.show"] = "Mostrar lo que encontró el modelo",
            ["seg.hide"] = "Ocultar la superposición",
            ["seg.none"] = "No se reconoció nada en esta foto",
            ["seg.findAll"] = "Buscar todas las fotos con {0}",
            ["seg.coverage"] = "{0}% del encuadre",
            ["label.add"] = "Añadir palabra clave",
            ["label.remove"] = "Quitar esta palabra clave",
            ["label.rename"] = "Corregir esta etiqueta",
            ["label.saved"] = "Ahora se llama {0}",
            ["label.reverted"] = "Se restauró lo que dijo el modelo",
            ["label.tagged"] = "Se añadió {0}",
            ["label.untagged"] = "Se quitó {0}",
            ["filter.object"] = "En la foto",

            // ---- faces -------------------------------------------------------------------
            ["faces.title"] = "Rostros",
            ["faces.show"] = "Mostrar",
            ["faces.show.people"] = "Una tarjeta por persona",
            ["faces.show.all"] = "Todos los rostros",
            ["faces.appears"] = "En {0} fotos",
            ["faces.appearsOne"] = "En 1 foto",
            ["faces.people"] = "{0} personas en {1} fotos",
            ["faces.nav.photos"] = "Fotos",
            ["faces.nav.faces"] = "Rostros",
            ["faces.count"] = "{0} rostros en {1} fotos",
            ["faces.countOne"] = "1 rostro en 1 foto",
            ["faces.scan"] = "Buscar rostros",
            ["faces.scanning"] = "Buscando rostros",
            ["faces.scanned"] = "Se examinaron {0} fotos y se encontraron {1} rostros",
            ["faces.rescan"] = "Volver a buscar",
            ["faces.order"] = "Orden",
            ["faces.order.prominence"] = "Más destacados",
            ["faces.order.newest"] = "Foto más reciente",
            ["faces.order.oldest"] = "Foto más antigua",
            ["faces.order.confidence"] = "Más seguros",
            ["faces.confidence"] = "Certeza",
            ["faces.confidence.all"] = "Todo lo encontrado",
            ["faces.confidence.likely"] = "Rostros probables",
            ["faces.confidence.certain"] = "Solo rostros seguros",
            ["faces.open"] = "Abrir la foto de este rostro",
            ["faces.inPhoto"] = "En {0}",
            ["faces.share"] = "{0}% del encuadre",
            ["faces.empty.title"] = "Aún no hay rostros",
            ["faces.empty.body"] = "Todavía no se ha buscado rostros aquí. La búsqueda se hace en este equipo y ninguna foto sale de él.",
            ["faces.none.title"] = "No hay rostros en esta fototeca",
            ["faces.none.body"] = "Se examinaron todas las fotos y ninguna tiene un rostro.",
            ["faces.nomodel.title"] = "El detector de rostros no está instalado",
            ["faces.nomodel.body"] = "Coloca face_yunet_2023mar.onnx en {0} y vuelve a abrir esta página.",
            ["faces.privacy"] = "Los rostros se detectan en este equipo. No se sube nada.",

            // ---- this person ------------------------------------------------------------
            ["person.title"] = "Esta persona",
            ["person.count"] = "{0} fotos",
            ["person.countOne"] = "1 foto",
            ["person.back"] = "Todos los rostros",
            ["person.find"] = "Buscar todas las fotos de esta persona",
            ["person.match"] = "Coincidencia",
            ["person.match.strict"] = "Solo seguras",
            ["person.match.normal"] = "Equilibrada",
            ["person.match.loose"] = "Incluir dudosas",
            ["person.alike"] = "{0}% de parecido",
            ["person.thisOne"] = "El rostro que elegiste",
            ["person.picked"] = "Elegido",
            ["person.none.title"] = "Solo esta foto",
            ["person.none.body"] = "Ninguna otra foto de la fototeca tiene un rostro lo bastante parecido a este.",
            ["person.small.title"] = "Este rostro es demasiado pequeño para buscarlo",
            ["person.small.body"] = "Comparar rostros necesita más detalle del que tiene este. Prueba con una foto donde la persona esté más cerca de la cámara.",
            ["person.off.title"] = "La comparación de rostros no está configurada",
            ["person.off.body"] = "Coloca face_sface_2021dec.onnx en {0} y vuelve a buscar rostros.",
            ["person.stale"] = "Se detectó antes de configurar la comparación. Vuelve a buscar rostros para poder buscar por persona.",
            ["person.caution"] = "PixelFlux compara rostros por su aspecto, no por nombre. Comprueba el resultado antes de fiarte.",

            ["viewer.resetZoom"] = "Restablecer zoom",
            ["language"] = "Idioma",
        },

        ["ja"] = new(StringComparer.Ordinal)
        {
            ["search.placeholder"] = "夕暮れの浜辺にいる犬",
            ["search.corrected"] = "「{0}」→ {1}",
            ["search.byMeaning"] = "意味による一致を含む",
            ["search.describe"] = "写真を解析",
            ["describe.action"] = "写真を読み取る",
            ["describe.working"] = "写真を読み取っています",
            ["describe.done"] = "{0}枚を読み取りました",
            ["describe.coverage"] = "{1}枚中{0}枚を読み取り済み",
            ["plate.described"] = "PixelFlux が読み取った内容",
            ["search.describing"] = "写真を解析しています",
            ["search.described"] = "{1}枚中{0}枚が意味で検索できます",
            ["search.label"] = "写真を検索",

            ["tool.filters"] = "絞り込み",
            ["tool.sort"] = "並べ替え",
            ["tool.smaller"] = "小さく表示",
            ["tool.larger"] = "大きく表示",
            ["tool.add"] = "写真を追加",
            ["tool.importing"] = "読み込み中…",
            ["tool.shortcuts"] = "キーボードショートカット",

            ["sort.captured.desc"] = "新しい順",
            ["sort.captured.asc"] = "古い順",
            ["sort.indexed.desc"] = "追加した順",
            ["sort.filename"] = "ファイル名",
            ["sort.rating.desc"] = "評価の高い順",
            ["sort.size.desc"] = "サイズの大きい順",
            ["sort.camera"] = "カメラ別",
            ["sort.folder"] = "フォルダー別",
            ["sort.shuffle"] = "シャッフル",

            ["heading.all"] = "すべての写真",
            ["heading.search"] = "検索",
            ["heading.filtered"] = "絞り込み結果",
            ["heading.frames"] = "{0}枚 · {1}",

            ["filter.title"] = "絞り込み",
            ["filter.clearAll"] = "すべて解除",
            ["filter.rating"] = "評価",
            ["filter.camera"] = "カメラ",
            ["filter.folder"] = "フォルダー",
            ["filter.tag"] = "タグ",
            ["filter.city"] = "都市",
            ["filter.country"] = "国",
            ["filter.place"] = "場所",
            ["filter.favourites"] = "お気に入りのみ",
            ["filter.starsAndUp"] = "★{0}以上",
            ["filter.any"] = "すべて",
            ["filter.remove"] = "この条件を外す",
            ["filter.active"] = "適用中の条件",

            ["rail.label"] = "タイムライン",
            ["rail.showAll"] = "すべての写真を表示",
            ["rail.noPhotos"] = "写真がありません",
            ["rail.emptyMonths"] = "写真のない{0}か月",
            ["rail.notAnalysed"] = "未解析のものがあります",

            ["empty.none.title"] = "まだ写真がありません",
            ["empty.none.body"] = "フォルダーを指定すると、PixelFluxがすべての画像を読み取り、撮影日時と場所を調べ、バックグラウンドで内容の記述を始めます。",
            ["empty.filtered.title"] = "該当する写真がありません",
            ["empty.filtered.body"] = "これらの条件すべてに当てはまる写真はありません。上の条件をひとつ外すか、すべて解除してやり直してください。",
            ["empty.filtered.action"] = "条件をすべて解除",

            ["frame.unreadable"] = "このファイルは読み取れません",
            ["frame.queued"] = "解析待ち",

            ["status.photos"] = "枚",
            ["status.shown"] = "表示中",
            ["status.unreadable"] = "読み取り不可",
            ["status.idle"] = "待機中",
            ["status.reading"] = "ファイル読み取り中",
            ["status.analysing"] = "{0}枚を解析中",
            ["status.queued"] = "{0}枚待機",
            ["pipeline.describe"] = "{0} を読み取り中",
            ["pipeline.segment"] = "{0} の物体を検出中",
            ["pipeline.faces"] = "{0} の顔を検出中",
            ["pipeline.embed"] = "{0} を索引中",
            ["pipeline.waiting"] = "未解析 {0}枚",
            ["analysis.title"] = "解析",
            ["analysis.stage.describe"] = "読み取り",
            ["analysis.stage.segment"] = "物体",
            ["analysis.stage.faces"] = "顔",
            ["analysis.stage.embed"] = "検索索引",
            ["analysis.stuck"] = "{0}枚を読み取れませんでした。",
            ["analysis.when"] = "実行する時間帯",
            ["analysis.mode.always"] = "起動中はいつでも",
            ["analysis.mode.window"] = "夜間",
            ["analysis.mode.off"] = "指示したときだけ",
            ["analysis.from"] = "開始",
            ["analysis.to"] = "終了",
            ["analysis.gap"] = "写真ごとの待ち時間",
            ["analysis.gapValue"] = "{0}秒",
            ["analysis.runNow"] = "今すぐ実行",
            ["analysis.opensAt"] = "次回 {0}",
            ["analysis.hardware"] = "ハードウェア",
            ["analysis.accel.auto"] = "自動",
            ["analysis.accel.cpu"] = "CPU",
            ["analysis.accel.gpu"] = "GPU",
            ["analysis.accel.npu"] = "NPU",
            ["analysis.accelRestart"] = "次回の起動時に適用されます。",
            ["plate.analysis"] = "未処理",
            ["plate.analysisWaiting"] = "{0} を待機中",
            ["plate.analysisStuck"] = "この写真では {0} を実行できませんでした",
            ["analysis.accelUsedBy"] = "{0} に使用。他は CPU の方が高速です。",
            ["analysis.accelNone"] = "すべて CPU で実行します。",
            ["analysis.retry"] = "再試行",
            ["setup.title"] = "高度な機能を有効にする",
            ["setup.preamble"] = "PixelFlux はオフラインで動作しますが、写真を読み取るモデルは同梱するには大きすぎ、再配布も認められていません。ダウンロードはこのアプリが唯一ネットワークを使う場面です。すべて任意で、後回しにできます。",
            ["setup.get"] = "ダウンロード",
            ["setup.getAll"] = "すべてダウンロード ({0})",
            ["setup.installed"] = "インストール済み",
            ["setup.stop"] = "停止",
            ["setup.later"] = "後で",
            ["setup.done"] = "完了",
            ["sources.title"] = "写真の保存場所",
            ["sources.empty"] = "フォルダーがまだありません。追加すると、その中のすべてを取り込みます。",
            ["sources.add"] = "フォルダーを追加…",
            ["sources.scan"] = "新しい写真を探す",
            ["sources.scanning"] = "検索中…",
            ["sources.remove"] = "削除",
            ["sources.removeHint"] = "このフォルダーからの取り込みを停止します。取り込み済みの写真は残ります。",
            ["sources.missing"] = "アクセスできません",
            ["sources.close"] = "閉じる",
            ["setup.copyleft"] = "これは AGPL-3.0 です。個人の写真に使う分には問題ありませんが、これを含むビルドの配布や、改変した PixelFlux のサービス提供にはソース公開の義務が生じます。",
            ["setup.readTerms"] = "ライセンスを読む",
            ["status.imported"] = "{0}枚追加 · {1}枚は既知 · {2}秒",
            ["status.noAlbum"] = "アルバムフォルダーが見つかりません",

            ["viewer.close"] = "閉じる",
            ["viewer.previous"] = "前の写真",
            ["viewer.next"] = "次の写真",
            ["plate.frame"] = "ファイル",
            ["plate.taken"] = "撮影日時",
            ["plate.filed"] = "保存日時",
            ["plate.camera"] = "カメラ",
            ["plate.exposure"] = "露出",
            ["plate.size"] = "サイズ",
            ["plate.place"] = "場所",
            ["plate.saw"] = "PixelFluxが見たもの",
            ["plate.notAnalysed"] = "未解析",
            ["plate.queued"] = "待機中",
            ["plate.fromExif"] = "カメラのEXIFより",
            ["plate.fromFile"] = "EXIFに日付なし — ファイルのタイムスタンプを使用",

            ["keys.title"] = "キーボードショートカット",
            ["keys.close"] = "閉じる",
            ["keys.group.navigate"] = "移動",
            ["keys.group.filter"] = "検索と絞り込み",
            ["keys.group.view"] = "表示",
            ["keys.move"] = "写真間を移動",
            ["keys.open"] = "選択した写真を開く",
            ["keys.firstLast"] = "最初 / 最後の写真",
            ["keys.page"] = "ページ送り",
            ["keys.search"] = "検索へ移動",
            ["keys.toggleFilters"] = "絞り込みの表示切替",
            ["keys.clear"] = "条件を解除、または閉じる",
            ["keys.zoom"] = "表示サイズの変更",
            ["keys.help"] = "この一覧",

            ["crash.title"] = "PixelFluxでエラーが発生しました",
            ["crash.body"] = "ライブラリは変更されていません。再読み込みで続行できます。繰り返す場合は下の詳細をご報告ください。",
            ["crash.reload"] = "表示を再読み込み",

            ["notFound.title"] = "ここには何もありません",
            ["notFound.body"] = "そのアドレスはPixelFlux内のどこにも一致しません。写真に戻ってください。",
            ["notFound.action"] = "すべての写真",

            ["albums.title"] = "アルバム",
            ["albums.new"] = "新しいアルバム",
            ["albums.namePlaceholder"] = "アルバム名",
            ["albums.create"] = "作成",
            ["albums.cancel"] = "キャンセル",
            ["albums.none"] = "アルバムがありません",
            ["albums.all"] = "すべての写真",
            ["albums.empty"] = "このアルバムは空です。写真を選んで追加してください。",
            ["albums.rename"] = "名前を変更",
            ["albums.delete"] = "アルバムを削除",
            ["albums.deleteHint"] = "アルバムのみ削除します。写真はそのまま残ります。",
            ["albums.dropHere"] = "ドロップで追加",
            ["albums.duplicateName"] = "同じ名前のアルバムがすでにあります",

            ["select.count"] = "{0}枚を選択中",
            ["select.clear"] = "選択を解除",
            ["select.all"] = "すべて選択",
            ["select.toggle"] = "この写真を選択",
            ["select.addTo"] = "アルバムに追加",
            ["select.moveTo"] = "アルバムへ移動",
            ["select.removeFrom"] = "このアルバムから外す",
            ["select.added"] = "{0}枚を{1}に追加しました",
            ["select.moved"] = "{0}枚を{1}へ移動しました",
            ["select.removed"] = "{0}枚を{1}から外しました",
            ["select.alreadyIn"] = "すでにこのアルバムにあります",

            ["seg.title"] = "この写真に写っているもの",
            ["seg.show"] = "検出結果を表示",
            ["seg.hide"] = "重ね表示を隠す",
            ["seg.none"] = "認識できるものはありませんでした",
            ["seg.findAll"] = "{0}が写っている写真をすべて表示",
            ["seg.coverage"] = "画面の{0}%",
            ["label.add"] = "キーワードを追加",
            ["label.remove"] = "このキーワードを削除",
            ["label.rename"] = "このラベルを修正",
            ["label.saved"] = "{0}に変更しました",
            ["label.reverted"] = "モデルの判定に戻しました",
            ["label.tagged"] = "{0}を追加しました",
            ["label.untagged"] = "{0}を削除しました",
            ["filter.object"] = "写っているもの",

            // ---- faces -------------------------------------------------------------------
            ["faces.title"] = "顔",
            ["faces.show"] = "表示",
            ["faces.show.people"] = "1人につき1枚",
            ["faces.show.all"] = "すべての顔",
            ["faces.appears"] = "{0}枚の写真",
            ["faces.appearsOne"] = "1枚の写真",
            ["faces.people"] = "{1}枚の写真に{0}人",
            ["faces.nav.photos"] = "写真",
            ["faces.nav.faces"] = "顔",
            ["faces.count"] = "{1}枚の写真に{0}件の顔",
            ["faces.countOne"] = "1枚の写真に1件の顔",
            ["faces.scan"] = "顔を検出",
            ["faces.scanning"] = "顔を検出しています",
            ["faces.scanned"] = "{0}枚を調べて{1}件の顔が見つかりました",
            ["faces.rescan"] = "もう一度検出",
            ["faces.order"] = "並び順",
            ["faces.order.prominence"] = "目立つ順",
            ["faces.order.newest"] = "写真の新しい順",
            ["faces.order.oldest"] = "写真の古い順",
            ["faces.order.confidence"] = "確度の高い順",
            ["faces.confidence"] = "確度",
            ["faces.confidence.all"] = "見つかったすべて",
            ["faces.confidence.likely"] = "顔の可能性が高いもの",
            ["faces.confidence.certain"] = "確実な顔のみ",
            ["faces.open"] = "この顔が写っている写真を開く",
            ["faces.inPhoto"] = "{0}",
            ["faces.share"] = "画面の{0}%",
            ["faces.empty.title"] = "まだ顔はありません",
            ["faces.empty.body"] = "まだ顔の検出を行っていません。検出はこのパソコン内で行われ、写真が外部に出ることはありません。",
            ["faces.none.title"] = "このライブラリに顔はありません",
            ["faces.none.body"] = "すべての写真を調べましたが、顔は写っていませんでした。",
            ["faces.nomodel.title"] = "顔検出モデルがインストールされていません",
            ["faces.nomodel.body"] = "face_yunet_2023mar.onnx を {0} に置いてから、このページを開き直してください。",
            ["faces.privacy"] = "顔の検出はこのパソコン内で行われます。アップロードは一切ありません。",

            // ---- this person ------------------------------------------------------------
            ["person.title"] = "この人",
            ["person.count"] = "{0}枚の写真",
            ["person.countOne"] = "1枚の写真",
            ["person.back"] = "すべての顔",
            ["person.find"] = "この人が写っている写真をすべて探す",
            ["person.match"] = "一致度",
            ["person.match.strict"] = "確実なもののみ",
            ["person.match.normal"] = "標準",
            ["person.match.loose"] = "可能性のあるものも含める",
            ["person.alike"] = "類似度{0}%",
            ["person.thisOne"] = "選んだ顔",
            ["person.picked"] = "選択中",
            ["person.none.title"] = "この1枚だけ",
            ["person.none.body"] = "ライブラリの他の写真に、これと十分に似た顔はありません。",
            ["person.small.title"] = "この顔は小さすぎて検索できません",
            ["person.small.body"] = "顔を比べるにはもっと細部が必要です。人物がカメラに近い写真でお試しください。",
            ["person.off.title"] = "顔の照合が設定されていません",
            ["person.off.body"] = "face_sface_2021dec.onnx を {0} に置いてから、もう一度顔を検出してください。",
            ["person.stale"] = "照合の設定前に検出された顔です。人物で探すには、もう一度顔を検出してください。",
            ["person.caution"] = "PixelFlux は名前ではなく見た目で顔を照合します。信じる前にご確認ください。",

            ["viewer.resetZoom"] = "ズームをリセット",
            ["language"] = "言語",
        },

        ["ar"] = new(StringComparer.Ordinal)
        {
            ["search.placeholder"] = "كلاب على الشاطئ عند الغروب",
            ["search.corrected"] = "«{0}» ← {1}",
            ["search.byMeaning"] = "يشمل التطابق بالمعنى",
            ["search.describe"] = "تحليل الصور",
            ["describe.action"] = "قراءة الصور",
            ["describe.working"] = "جارٍ قراءة الصور",
            ["describe.done"] = "تمت قراءة {0} صورة",
            ["describe.coverage"] = "تمت قراءة {0} من {1} صورة",
            ["plate.described"] = "ما قرأه PixelFlux",
            ["search.describing"] = "جارٍ تحليل الصور",
            ["search.described"] = "{0} من {1} صورة قابلة للبحث بالمعنى",
            ["search.label"] = "ابحث في صورك",

            ["tool.filters"] = "عوامل التصفية",
            ["tool.sort"] = "الترتيب",
            ["tool.smaller"] = "إطارات أصغر",
            ["tool.larger"] = "إطارات أكبر",
            ["tool.add"] = "إضافة صور",
            ["tool.importing"] = "جارٍ الاستيراد…",
            ["tool.shortcuts"] = "اختصارات لوحة المفاتيح",

            ["sort.captured.desc"] = "الأحدث أولاً",
            ["sort.captured.asc"] = "الأقدم أولاً",
            ["sort.indexed.desc"] = "المضافة حديثاً",
            ["sort.filename"] = "اسم الملف",
            ["sort.rating.desc"] = "الأعلى تقييماً",
            ["sort.size.desc"] = "الأكبر حجماً",
            ["sort.camera"] = "حسب الكاميرا",
            ["sort.folder"] = "حسب المجلد",
            ["sort.shuffle"] = "ترتيب عشوائي",

            ["heading.all"] = "كل الصور",
            ["heading.search"] = "بحث",
            ["heading.filtered"] = "مُصفّاة",
            ["heading.frames"] = "{0} صورة · {1}",

            ["filter.title"] = "تصفية",
            ["filter.clearAll"] = "مسح الكل",
            ["filter.rating"] = "التقييم",
            ["filter.camera"] = "الكاميرا",
            ["filter.folder"] = "المجلد",
            ["filter.tag"] = "الوسم",
            ["filter.city"] = "المدينة",
            ["filter.country"] = "البلد",
            ["filter.place"] = "المكان",
            ["filter.favourites"] = "المفضّلة فقط",
            ["filter.starsAndUp"] = "{0} نجوم فأكثر",
            ["filter.any"] = "الكل",
            ["filter.remove"] = "إزالة هذا الفلتر",
            ["filter.active"] = "عوامل التصفية النشطة",

            ["rail.label"] = "الخط الزمني",
            ["rail.showAll"] = "عرض كل الصور",
            ["rail.noPhotos"] = "لا صور بعد",
            ["rail.emptyMonths"] = "{0} شهراً بلا صور",
            ["rail.notAnalysed"] = "بعضها لم يُحلَّل بعد",

            ["empty.none.title"] = "لا صور بعد",
            ["empty.none.body"] = "وجّه PixelFlux إلى مجلد وسيقرأ كل صورة، ويستنتج متى وأين التُقطت، ويبدأ بوصفها في الخلفية.",
            ["empty.filtered.title"] = "لا نتائج مطابقة",
            ["empty.filtered.body"] = "لا توجد صور تحقق كل هذه الشروط معاً. أزل أحدها بالأعلى، أو امسحها كلها وابدأ من جديد.",
            ["empty.filtered.action"] = "مسح كل عوامل التصفية",

            ["frame.unreadable"] = "تعذّرت قراءة هذا الملف",
            ["frame.queued"] = "في انتظار التحليل",

            ["status.photos"] = "صورة",
            ["status.shown"] = "معروضة",
            ["status.unreadable"] = "غير مقروءة",
            ["status.idle"] = "خامل",
            ["status.reading"] = "جارٍ قراءة الملفات",
            ["status.analysing"] = "جارٍ تحليل {0}",
            ["status.queued"] = "{0} في الانتظار",
            ["pipeline.describe"] = "قراءة {0}",
            ["pipeline.segment"] = "البحث عن أشياء في {0}",
            ["pipeline.faces"] = "البحث عن وجوه في {0}",
            ["pipeline.embed"] = "فهرسة {0}",
            ["pipeline.waiting"] = "{0} في انتظار التحليل",
            ["analysis.title"] = "التحليل",
            ["analysis.stage.describe"] = "القراءة",
            ["analysis.stage.segment"] = "الأشياء",
            ["analysis.stage.faces"] = "الوجوه",
            ["analysis.stage.embed"] = "فهرس البحث",
            ["analysis.stuck"] = "تعذّرت قراءة {0}.",
            ["analysis.when"] = "وقت التشغيل",
            ["analysis.mode.always"] = "أثناء فتح التطبيق",
            ["analysis.mode.window"] = "ليلاً",
            ["analysis.mode.off"] = "عند الطلب فقط",
            ["analysis.from"] = "من",
            ["analysis.to"] = "إلى",
            ["analysis.gap"] = "الانتظار بين الصور",
            ["analysis.gapValue"] = "{0} ث",
            ["analysis.runNow"] = "شغّل الآن",
            ["analysis.opensAt"] = "التشغيل القادم {0}",
            ["analysis.hardware"] = "العتاد",
            ["analysis.accel.auto"] = "تلقائي",
            ["analysis.accel.cpu"] = "المعالج",
            ["analysis.accel.gpu"] = "الرسوميات",
            ["analysis.accel.npu"] = "العصبي",
            ["analysis.accelRestart"] = "يسري عند تشغيل PixelFlux في المرة القادمة.",
            ["plate.analysis"] = "قيد الانتظار",
            ["plate.analysisWaiting"] = "في انتظار {0}",
            ["plate.analysisStuck"] = "تعذّر تشغيل {0} على هذه الصورة",
            ["analysis.accelUsedBy"] = "يُستخدم لـ {0}. الباقي أسرع على المعالج.",
            ["analysis.accelNone"] = "كل شيء يعمل على المعالج.",
            ["analysis.retry"] = "أعد المحاولة",
            ["setup.title"] = "تفعيل الميزات الذكية",
            ["setup.preamble"] = "يعمل PixelFlux دون اتصال، لكن النماذج التي تقرأ صورك أكبر من أن تُشحن معه وليست ملكنا لإعادة توزيعها. تنزيل أحدها هو المرة الوحيدة التي يستخدم فيها التطبيق الشبكة. كلها اختيارية ويمكن تأجيلها.",
            ["setup.get"] = "تنزيل",
            ["setup.getAll"] = "تنزيل الكل ({0})",
            ["setup.installed"] = "مثبَّت",
            ["setup.stop"] = "إيقاف",
            ["setup.later"] = "ليس الآن",
            ["setup.done"] = "تم",
            ["sources.title"] = "أين توجد صورك",
            ["sources.empty"] = "لا توجد مجلدات بعد. أضف مجلداً وسيستورد PixelFlux كل ما بداخله.",
            ["sources.add"] = "إضافة مجلد…",
            ["sources.scan"] = "ابحث عن صور جديدة",
            ["sources.scanning"] = "جارٍ البحث…",
            ["sources.remove"] = "إزالة",
            ["sources.removeHint"] = "إيقاف الاستيراد من هذا المجلد. تبقى الصور المستوردة.",
            ["sources.missing"] = "غير متاح",
            ["sources.close"] = "إغلاق",
            ["setup.copyleft"] = "هذا النموذج بترخيص AGPL-3.0. لا بأس باستخدامه لصورك؛ أما توزيع نسخة تتضمنه أو تشغيل PixelFlux معدَّلاً كخدمة فيلزمك بنشر شفرتك.",
            ["setup.readTerms"] = "اقرأ الشروط",
            ["status.imported"] = "أُضيفت {0} · {1} معروفة مسبقاً · {2}ث",
            ["status.noAlbum"] = "لم يُعثر على مجلد الألبوم",

            ["viewer.close"] = "إغلاق",
            ["viewer.previous"] = "الصورة السابقة",
            ["viewer.next"] = "الصورة التالية",
            ["plate.frame"] = "الملف",
            ["plate.taken"] = "التُقطت",
            ["plate.filed"] = "حُفظت",
            ["plate.camera"] = "الكاميرا",
            ["plate.exposure"] = "التعريض",
            ["plate.size"] = "الحجم",
            ["plate.place"] = "المكان",
            ["plate.saw"] = "ما رآه PixelFlux",
            ["plate.notAnalysed"] = "لم يُحلَّل بعد",
            ["plate.queued"] = "في الانتظار",
            ["plate.fromExif"] = "من بيانات EXIF للكاميرا",
            ["plate.fromFile"] = "لا تاريخ في EXIF — أُخذ من طابع وقت الملف",

            ["keys.title"] = "اختصارات لوحة المفاتيح",
            ["keys.close"] = "إغلاق",
            ["keys.group.navigate"] = "التنقل",
            ["keys.group.filter"] = "البحث والتصفية",
            ["keys.group.view"] = "العرض",
            ["keys.move"] = "التنقل بين الصور",
            ["keys.open"] = "فتح الصورة المحددة",
            ["keys.firstLast"] = "الصورة الأولى / الأخيرة",
            ["keys.page"] = "صفحة للأعلى / للأسفل",
            ["keys.search"] = "الانتقال إلى البحث",
            ["keys.toggleFilters"] = "إظهار أو إخفاء التصفية",
            ["keys.clear"] = "مسح التصفية أو إغلاق المفتوح",
            ["keys.zoom"] = "تصغير / تكبير الإطارات",
            ["keys.help"] = "هذه القائمة",

            ["crash.title"] = "حدث خطأ في PixelFlux",
            ["crash.body"] = "مكتبتك لم تُمَس — لم يُكتب أي شيء. أعد التحميل للمتابعة، وإن تكرر الأمر فأبلغ عن التفاصيل أدناه.",
            ["crash.reload"] = "إعادة تحميل العرض",

            ["notFound.title"] = "لا شيء هنا",
            ["notFound.body"] = "هذا العنوان لا يطابق أي شيء في PixelFlux. عُد إلى صورك.",
            ["notFound.action"] = "كل الصور",

            ["albums.title"] = "الألبومات",
            ["albums.new"] = "ألبوم جديد",
            ["albums.namePlaceholder"] = "اسم الألبوم",
            ["albums.create"] = "إنشاء",
            ["albums.cancel"] = "إلغاء",
            ["albums.none"] = "لا ألبومات بعد",
            ["albums.all"] = "كل الصور",
            ["albums.empty"] = "هذا الألبوم فارغ. حدّد صوراً وأضفها هنا.",
            ["albums.rename"] = "إعادة تسمية",
            ["albums.delete"] = "حذف الألبوم",
            ["albums.deleteHint"] = "يحذف الألبوم فقط. صورك تبقى كما هي.",
            ["albums.dropHere"] = "أفلت للإضافة",
            ["albums.duplicateName"] = "يوجد ألبوم بهذا الاسم بالفعل",

            ["select.count"] = "{0} محددة",
            ["select.clear"] = "إلغاء التحديد",
            ["select.all"] = "تحديد الكل",
            ["select.toggle"] = "تحديد هذه الصورة",
            ["select.addTo"] = "إضافة إلى ألبوم",
            ["select.moveTo"] = "نقل إلى ألبوم",
            ["select.removeFrom"] = "إزالة من هذا الألبوم",
            ["select.added"] = "أُضيفت {0} إلى {1}",
            ["select.moved"] = "نُقلت {0} إلى {1}",
            ["select.removed"] = "أُزيلت {0} من {1}",
            ["select.alreadyIn"] = "موجودة في هذا الألبوم بالفعل",

            ["seg.title"] = "ما في هذه الصورة",
            ["seg.show"] = "إظهار ما وجده النموذج",
            ["seg.hide"] = "إخفاء الطبقة",
            ["seg.none"] = "لم يُتعرَّف على شيء في هذه الصورة",
            ["seg.findAll"] = "عرض كل الصور التي تحتوي على {0}",
            ["seg.coverage"] = "{0}٪ من الإطار",
            ["label.add"] = "إضافة كلمة مفتاحية",
            ["label.remove"] = "إزالة هذه الكلمة",
            ["label.rename"] = "تصحيح هذه التسمية",
            ["label.saved"] = "أصبح اسمه {0}",
            ["label.reverted"] = "عاد إلى ما قاله النموذج",
            ["label.tagged"] = "تمت إضافة {0}",
            ["label.untagged"] = "تمت إزالة {0}",
            ["filter.object"] = "في الصورة",

            // ---- faces -------------------------------------------------------------------
            ["faces.title"] = "الوجوه",
            ["faces.show"] = "العرض",
            ["faces.show.people"] = "بطاقة لكل شخص",
            ["faces.show.all"] = "كل الوجوه",
            ["faces.appears"] = "في {0} صورة",
            ["faces.appearsOne"] = "في صورة واحدة",
            ["faces.people"] = "{0} أشخاص في {1} صورة",
            ["faces.nav.photos"] = "الصور",
            ["faces.nav.faces"] = "الوجوه",
            ["faces.count"] = "{0} وجهًا في {1} صورة",
            ["faces.countOne"] = "وجه واحد في صورة واحدة",
            ["faces.scan"] = "البحث عن الوجوه",
            ["faces.scanning"] = "جارٍ البحث عن الوجوه",
            ["faces.scanned"] = "تم فحص {0} صورة والعثور على {1} وجهًا",
            ["faces.rescan"] = "إعادة البحث",
            ["faces.order"] = "الترتيب",
            ["faces.order.prominence"] = "الأبرز",
            ["faces.order.newest"] = "أحدث صورة",
            ["faces.order.oldest"] = "أقدم صورة",
            ["faces.order.confidence"] = "الأكثر تأكيدًا",
            ["faces.confidence"] = "درجة التأكد",
            ["faces.confidence.all"] = "كل ما عُثر عليه",
            ["faces.confidence.likely"] = "الوجوه المرجَّحة",
            ["faces.confidence.certain"] = "الوجوه المؤكدة فقط",
            ["faces.open"] = "فتح الصورة التي يظهر فيها هذا الوجه",
            ["faces.inPhoto"] = "في {0}",
            ["faces.share"] = "{0}٪ من الإطار",
            ["faces.empty.title"] = "لا توجد وجوه بعد",
            ["faces.empty.body"] = "لم يُبحث عن وجوه هنا بعد. يجري البحث على هذا الجهاز ولا تغادره أي صورة.",
            ["faces.none.title"] = "لا توجد وجوه في هذه المكتبة",
            ["faces.none.body"] = "تم فحص كل الصور ولم يظهر أي وجه فيها.",
            ["faces.nomodel.title"] = "أداة كشف الوجوه غير مثبَّتة",
            ["faces.nomodel.body"] = "ضع الملف face_yunet_2023mar.onnx في {0} ثم أعد فتح هذه الصفحة.",
            ["faces.privacy"] = "يجري كشف الوجوه على هذا الجهاز. لا يُرفع أي شيء.",

            // ---- this person ------------------------------------------------------------
            ["person.title"] = "هذا الشخص",
            ["person.count"] = "{0} صورة",
            ["person.countOne"] = "صورة واحدة",
            ["person.back"] = "كل الوجوه",
            ["person.find"] = "البحث عن كل صور هذا الشخص",
            ["person.match"] = "التطابق",
            ["person.match.strict"] = "المؤكد فقط",
            ["person.match.normal"] = "متوازن",
            ["person.match.loose"] = "مع المحتمل",
            ["person.alike"] = "تشابه {0}٪",
            ["person.thisOne"] = "الوجه الذي اخترته",
            ["person.picked"] = "المختار",
            ["person.none.title"] = "هذه الصورة فقط",
            ["person.none.body"] = "لا توجد صورة أخرى في المكتبة فيها وجه قريب بما يكفي من هذا.",
            ["person.small.title"] = "هذا الوجه أصغر من أن يُبحث عنه",
            ["person.small.body"] = "يحتاج التطابق إلى تفاصيل أكثر مما في هذا الوجه. جرّب صورة يظهر فيها الشخص أقرب إلى الكاميرا.",
            ["person.off.title"] = "مطابقة الوجوه غير مُعدّة",
            ["person.off.body"] = "ضع الملف face_sface_2021dec.onnx في {0} ثم أعد البحث عن الوجوه.",
            ["person.stale"] = "عُثر عليه قبل إعداد المطابقة. أعد البحث عن الوجوه للبحث حسب الشخص.",
            ["person.caution"] = "يُطابق PixelFlux الوجوه بالشكل لا بالاسم. تحقّق قبل أن تثق بالنتيجة.",

            ["viewer.resetZoom"] = "إعادة ضبط التكبير",
            ["language"] = "اللغة",
        },
    };

    private Dictionary<string, string> _active = Catalogue["en"];

    /// <summary>The language currently in use.</summary>
    public Language Current { get; private set; } = Available[0];

    /// <summary>Whether the current language is written right to left.</summary>
    public bool IsRightToLeft => Current.RightToLeft;

    /// <summary>Raised after the language changes, so open views can re-render.</summary>
    public event Action? LanguageChanged;

    /// <summary>
    /// Selects a language, falling back to the closest available one.
    /// </summary>
    /// <param name="code">A BCP-47 code such as <c>es</c>, <c>es-MX</c>, or <c>ja-JP</c>.</param>
    /// <remarks>
    /// Region is stripped before matching, so <c>es-MX</c> and <c>es-ES</c> both land on Spanish
    /// rather than falling all the way back to English. Shipping every regional variant is how a
    /// localisation effort becomes unmaintainable; matching the language and ignoring the region
    /// covers almost every real user.
    /// </remarks>
    public void Use(string code)
    {
        string language = (code ?? "en").Split('-')[0];

        Language match = Available.FirstOrDefault(
            l => l.Code.Equals(language, StringComparison.OrdinalIgnoreCase),
            Available[0]);

        Current = match;
        _active = Catalogue[match.Code];

        // Dates, numbers, and the sort order of any list the UI builds must follow the chosen
        // language too. Setting only the strings produces the uncanny result of Japanese labels
        // above American-formatted dates.
        var culture = CultureInfo.GetCultureInfo(match.Code);
        CultureInfo.DefaultThreadCurrentCulture = culture;
        CultureInfo.DefaultThreadCurrentUICulture = culture;
        CultureInfo.CurrentCulture = culture;
        CultureInfo.CurrentUICulture = culture;

        LanguageChanged?.Invoke();
    }

    /// <summary>
    /// Adopts the operating system's language, if PixelFlux speaks it.
    /// </summary>
    /// <remarks>
    /// The <c>PIXELFLUX_LANG</c> environment variable overrides it. That exists so the app can
    /// be launched straight into Arabic or Japanese to check the layout, without clicking
    /// through the UI or changing the machine's own locale — which is the only practical way to
    /// catch a right-to-left regression before a speaker of the language does.
    /// </remarks>
    public void UseSystemLanguage()
        => Use(Environment.GetEnvironmentVariable("PIXELFLUX_LANG") ?? CultureInfo.CurrentUICulture.Name);

    /// <summary>Looks up a string by key.</summary>
    /// <param name="key">A dotted key, for example <c>gallery.empty.title</c>.</param>
    /// <returns>
    /// The translation, the English text if this language has not translated it, or the key
    /// itself if no language defines it.
    /// </returns>
    /// <remarks>
    /// Returning the key for a genuinely missing entry is deliberate. A blank label is invisible
    /// in testing and ships; a label reading <c>filter.camera</c> is impossible to miss and says
    /// exactly which entry to add.
    /// </remarks>
    public string this[string key]
    {
        get
        {
            if (_active.TryGetValue(key, out string? value))
            {
                return value;
            }

            return Catalogue["en"].TryGetValue(key, out string? english) ? english : key;
        }
    }

    /// <summary>Looks up a string and substitutes positional arguments into it.</summary>
    /// <param name="key">A dotted key whose text contains <c>{0}</c>-style placeholders.</param>
    /// <param name="args">Values to substitute.</param>
    /// <returns>The formatted string.</returns>
    /// <remarks>
    /// Placeholders rather than concatenation, always. Word order differs between languages —
    /// Arabic and Japanese both place the count differently from English — and a UI assembled by
    /// gluing fragments together can only ever be right in the language it was written in.
    /// </remarks>
    public string Format(string key, params object[] args)
        => string.Format(CultureInfo.CurrentCulture, this[key], args);

    /// <summary>Every key defined in English. Used by the test that proves no language has drifted.</summary>
    public static IReadOnlyCollection<string> AllKeys => Catalogue["en"].Keys;

    /// <summary>Keys defined for a language. Used by the coverage test.</summary>
    /// <param name="code">Language code.</param>
    /// <returns>The keys that language defines.</returns>
    public static IReadOnlyCollection<string> KeysFor(string code)
        => Catalogue.TryGetValue(code, out Dictionary<string, string>? map) ? map.Keys : [];
}
